### ISSUE TITLE
Film/Fiche range not set correctly

### ISSUE THREAD

**Issue by stwf** [stwf/BMD-X#23]
The Header details will not upload if the Film/Fiche Range is included as it gives too many 'parts'. I don't believe any of the other 'parts can be eliminated. I will include the range in my next page and send you the error message - I have already corrected it in this file.

**Comment by stwf** [comment]
Any suggestions of a resolution to this?

**Comment by resnape** [comment]
I believe the use of the two fields, Film/Fiche Range and Number/FreeBMDRef are driven by the Source>Format Entry.  Perhaps one solution would be to 'Defocus' one or other of the two subject fields depending upon Source>Format entry.  That way the number of parts available would not be exceeded.  However, I have not yet delved into the logical relationships of the Source>Format entry to the Number/FreeBMDRef and Film/Fiche Range entries.

**Comment by resnape** [comment]
I have done some research on this issue and it as I suspected it is the Source>Format entry that determines the format for the Source entries.   You may have already found this information, if so apologies for the duplication.

There are 4 type of Source Information Lines:

Fiche Info which entry format is  +F,Year,Quarter,FicheRange,FicheNumber,Source,TranscriptionDate.
Microfilm Info which entry format is +M,Year,Quarter,FilmRange,FilmNumber,Source, TranscriptionDate.
Book Info which entry format is  +B,Year,Quarter,Source,TranscriptionDate
Scan Info which entry format is  +S,Year,Quarter,FreeBMDReference,TranscriptionDate

The good news is that the Scan info is the only source type that is used with scans provided by the FreeBMD project.

So the simplistic solution may be to post a warning that the other three source types are not available which will leave the interface intact should FreeBMD choose to invoke the other source type entries.

**Comment by resnape** [comment]
Opps missed the comments regarding the source Modal window.  Perhaps the Film/Fiche Range and Source Location text entries should also be made unavailable.

**Comment by stwf** [comment]
ok, instead of disabling the interface, I just made the code smart enough to always give a valid Source line. Thanks so much for the research!

Fixed in 1.0.8
