### ISSUE TITLE
Missing "COMMENT" interface

### ISSUE THREAD

**Issue by resnape** [stwf/BMD-X#26]
There is no facility to enter a COMMENT.  
Current workaround is to enter a THEORY and edit the entry

**Comment by resnape** [comment]
Over the past year I have been dabbling, for my own edification, as to how to resolve this observation.  One simplistic solution I have tried my hand at programming is to add another Button on the main page as below:

![screen shot 2015-03-24 at 14 20 05](https://cloud.githubusercontent.com/assets/5701185/6803723/6e515f38-d231-11e4-90cb-6b2cb72af1f2.JPG)

The resulting entry screen and underlying supporting code is a duplication of that used for THEORY.

However, in my research of BMD I have come across another variation of a 'Comment' which is as follows:

Line starts with # (not followed by COMMENT or THEORY)
Used to give information about the transcription, e.g. # scan got very faint at this point. This type of comment will not be accessible from the search results but may be useful to syndicate coordinators when reviewing transcriptions. WinBMD and SpeedBMD use this type of comment to include information about the transcription immediately after the header with a format of #,volumeformat,username,syndicate,filename,date,flag,flag,... FreeBMD only takes note of the syndicate name from this line (this is the only instance in which FreeBMD uses information from this type of comment). 

I have designed, again solely for my edification, a solution to encompass all three variations if you are interested.

**Comment by stwf** [comment]
Yes! Thank you! Did you do the work in a branch? I look forward to a pull request

**Comment by resnape** [comment]
You will have to guide me one how to undertake a pull request:-)

A quick overview of my initial design is to use the existing Comment button to open the existing Modal window for Comment.  I have added a drop box with a selection of COMMENT, THEORY and # .  This is handled by a branch which I have called CommentType.  

I then use the result of this selection in BMDDocument.m to preload the output text line with the corresponding type of comment. 

Additionally the plan is to use this selection to load  the entry field Label and the description Label with the appropriate text.  

The coding for the existing OK and CANCEL buttons remains the same.

I was an Analyst/programmer from a previous life but I am still on a steep learning curve with x-code. I have come to a grinding halt as I have encountered an undeclared identifier error which I have not been able to resolve.  The subject identifier has been declared and is in scope, so it is head scratching time at the moment.  But as this is your application I will be more than happy to supply what I have done.

**Comment by stwf** [comment]
If you have the Source Control set up in XCode, choose 'BMD-X / master' from the workspaces and choose New Branch from the submenu, then make sure your changes are istill in that new branch, then commit everything and push the new branch back to github. You can create a pull request from that.

If you haven;t done that I recommend the GitHub Mac client, to create a branch and publish it to github.

**Comment by resnape** [comment]
Opps I have misunderstood the meaning of branch in this context (still on a steep learning curve).  

Unfortunately, as this was purely an exercise to understand  the basics of Xcode and to get my programming hat on again I omitted to set Source Control in Xcode.  Coupled with that oversight I did not create a branch from your MacBMD 1.0.6. and just downloaded a copy.  The problem I now have with setting up a branch is that I would be starting from the wrong baseline which will mean crafting what I have done from square one. 

I could put my efforts onto a proper Configuration Control footing but it would take a few days to get my act together.  Unless you have another suggestion?

**Comment by stwf** [comment]
no, I think everything should be fine.

Get the Mac Github client, then hit the + button and choose 'add'. Then select your code. Now the client should show a bunch of changes and that you are in the master branch. So if you then create a new branch from master, I think your changes will be brought into the new branch. Then just commit and sync.

Otherwise you can compress the whole thing and send it to me and I can give it a try.

If you are interested in getting the git basics I have always found the github tutorial to be very clear.

**Comment by resnape** [comment]
I have previously tried your suggestion which worked as advertised until I tried to create a branch from the master.  I am assuming that I had to Commit to Master before being able to create a branch, it is at this point the client reports an error with GIT config i.e name & email address thus terminating the process.  Therefore, the reference to HEAD (I assume which is the Master) cannot be resolved.

I shall give the GitHub tutorial a run to try and bottom out my undoubted finger trouble.

But if all else fails I shall zip the project and fire it off to you.

**Comment by stwf** [comment]
Hmm, the name and email can be set in the github client preferences. But don’t commit to master, make a new branch first, then do the commit.


On March 25, 2015 at 9:19:17 AM, Ralph E Snape (notifications@github.com) wrote:

I have previously tried your suggestion which worked as advertised until I tried to create a branch from the master. I am assuming that I had to Commit to Master before being able to create a branch, it is at this point the client reports an error with GIT config i.e name & email address thus terminating the process. Therefore, the reference to HEAD (I assume which is the Master) cannot be resolved.

I shall give the GitHub tutorial a run to try and bottom out my undoubted finger trouble.

But if all else fails I shall zip the project and fire it off to you.

**Comment by resnape** [comment]
![screen shot 2015-03-25 at 13 28 22](https://cloud.githubusercontent.com/assets/5701185/6825494/dc138584-d2f2-11e4-8384-b832ec0efa64.JPG)

Tried your suggestion and this is the result.  The tutorial concurs exactly with your instructions and has the same outcome.  

Entered my name and email in the github client preferences but even that posts a GIT Error.  I don't suppose that GitHub is not compatible with Yosemite?

**Comment by stwf** [comment]
Hmm, ok maybe downloaded repositories don’t have the necessary info. I am not a git expert by any means. I am not sure how to fix this. I guess the direct method would be to create a wheel new repository, cloning from github. Then make a new branch. Then just move the files you changed into the new folder. Git should handle figuring out what the differences are. Otherwise just go with the zip file.


On March 25, 2015 at 9:34:04 AM, Ralph E Snape (notifications@github.com) wrote:



Tried your suggestion and this is the result. The tutorial concurs exactly with your instructions and has the same outcome.

Entered my name and email in the github client preferences but even that posts a GIT Error. I don't suppose that GitHub is not compatible with Yosemite?

**Comment by resnape** [comment]
I shall research this further but in the meantime as I can't send a zip via this notification interface where do I send it?

**Comment by resnape** [comment]
OK.  Next try :-)  I have checked out a copy of Version 1.0.7 into xCode.  I have created a Branch of Version 1.0.7 and added the the code changes.  I still get the undeclared identifier error which I expected.  However, now I get a Linker error MACH O Linker ID error (linker command failed with exit code 1 (use -v to see invocation).  The Linker settings for this built are not the same as my internal projects but I am loath to try and tinker with the settings to try and resolve this problem.

Anyway, do I now commit everything and push the new branch back to github and then create a pull request from that?

**Comment by stwf** [comment]
yes exactly! thanks

**Comment by stwf** [comment]
otherwise you can send the code to stwf{at}yahoo{dot}com

**Comment by stwf** [comment]
ok, great. Thanks so much for the code and dialog box. It should be all up and working in 1.0.8, which is now up on the repository.
