### ISSUE TITLE
Incorrect position of Curser

### ISSUE THREAD

**Issue by resnape** [stwf/BMD-X#27]
The described issue arises only when a specific combination of entries (in this case for creating a file containing Death records) for a record is encountered.  

The observed situation only occurs when keying in a new entry that comprises a Surname and 2 Middle Names that follows an entry that comprises a Surname and 3 Middle Names.  After pushing TAB the curser moves to the next Middle Name entry when the expected action is for the Curser to move to the Date of entry field.

![screen shot 2014-11-05 at 08 32 05](https://cloud.githubusercontent.com/assets/5701185/4915158/6a24cbb6-64cc-11e4-91de-b79f2392c213.JPG)

**Comment by stwf** [comment]
ok, this has been fixed in 1.0.7 thanks
