### ISSUE TITLE
he "Date of Birth" Label is truncated when creating a transcription for Deaths for the Year 1971

### ISSUE THREAD

**Issue by resnape** [stwf/BMD-X#28]
Routine:
CFieldJumper.m (BMDDocument.xib)

Possible Resolution:
There does not appear to be an elegant or simple method of automatically sizing the Label using the number of text characters populating the Label.

As this is just a Label, employing the same methodology as used in CFieldJumper.m to adjust the size of the 'District field’ boundaries to resolve this issue would be overly complicated.

The simplistic solution would be to increase the ‘Width' value of the 'Frame Rectangle' for the “Spouse” Label, from 50 to 100 in BMDDocument.xib.  

Testing:
This solution has been tested for transcriptions involving Births, Deaths & Marriages and for Sample Years/Months for Deaths.  The results show that this solution has the desired outcome without any adverse impact with the test transcriptions.

**Comment by stwf** [comment]
great! Thanks! fixed in 1.0.7
