### ISSUE TITLE
In the opening BMD Document the District field start position is misaligned from the fields above (Surname Field and the 3rd Middle Name). 

### ISSUE THREAD

**Issue by resnape** [stwf/BMD-X#29]
Routine:
CFieldJumper.m

Possible Resolution:

This can be resolved by readjusting the District and Spouse Field widths in BMDDocument.xib.  However whilst recalculating the field widths it was found that a simplistic solution was to increase the ADJ_SIZE definition by a value of 5 to 205.

Testing:

This solution has been tested for transcriptions involving Births, Deaths & Marriages and for Sample Years/Months for Deaths.  The results show that this solution has resolved the misalignment issue.

**Comment by stwf** [comment]
thanks! Fixed in 1.0.7
