### ISSUE TITLE
Window autosizing

### ISSUE THREAD

**Issue by resnape** [stwf/BMD-X#30]
Quite by accident I have found a minor issue when resizing the main input window Horizontally.  The issue is depicted as follows:

![screen shot 2015-03-28 at 15 53 38](https://cloud.githubusercontent.com/assets/5701185/6881698/f8fcf6fe-d562-11e4-9820-5992bb681e15.JPG)

**Comment by stwf** [comment]
Is there a better way to handle this? Would you ever need that much space if we did enlarge the District field? That one would be easy. I guess the surname field too. It would be a pain to enlarge the middle name fields as the window changed sizes.

**Comment by resnape** [comment]
I have cranked up my old version of MacBMD and found that the main window cannot be resized either vertically or horizontally, however, the main entry text box itself can be scrolled vertically within the frame size.   I think this would be an elegant solution and a better interface.  I hope this helps?

**Comment by stwf** [comment]
OK, hopefully this has been addressed in 1.0.9. Thanks
