### ISSUE TITLE
Superfluous Theory Button

### ISSUE THREAD

**Issue by resnape** [stwf/BMD-X#34]
The Theory button and underlying code are now surplus to requirements as Theory etc are now available through the new comment... pull down selection.

![screen shot 2015-03-29 at 10 56 49](https://cloud.githubusercontent.com/assets/5701185/6884964/dbe349c4-d602-11e4-8e0f-10cc6042b93c.JPG)

**Comment by stwf** [comment]
OK, hopefully this has been addressed in 1.0.9. Thanks
