### ISSUE TITLE
Type of comment observations

### ISSUE THREAD

**Issue by resnape** [stwf/BMD-X#35]
Two further minor observations if I may?

Can the the type of comment default be set to 'COMMENT'?  Currently the selection starts with 'COMMENT' but if 'THEORY' or '#' are the used in same session the selection opens as the last one used.  i.e. if it was 'THEORY' after a 'COMMENT' then it would be 'THEORY' again in that session.

![screen shot 2015-03-29 at 11 02 47](https://cloud.githubusercontent.com/assets/5701185/6885014/8312f310-d604-11e4-9aef-ba880c73efae.JPG)

Can the the label for the text entry field reflect the type of comment and the comment type description?

i.e. Comment, Theory and # (Hash)

These are minor but would add polish to the new capability

**Comment by stwf** [comment]
OK, hopefully this has been addressed in 1.0.9. Thanks
