### ISSUE TITLE
Change of format to Transcription entries

### ISSUE THREAD

**Issue by resnape** [stwf/BMD-X#36]
I have found a change to the format to the Transcription entries in the 1.0.8 version of the software as compared to the preferred format in previous versions.

My observations are annotated in the following screen shot. 

![screen shot 2015-03-29 at 11 46 33](https://cloud.githubusercontent.com/assets/5701185/6885186/09466cc6-d60c-11e4-8d58-c2ca8f0be05c.JPG)

**Comment by resnape** [comment]
Hello Steve

I have done some further research regarding the use of Capitals:

Firstly, FreeBMD is not affected by capitalisation of names etc., - the assumption is that the upload processing does not test for capitals.  

However the Principles of Transcribing Data states that the transcription should be exactly as the record.  So if it is all in capitals do it that way, if all in lower case, etc.  Additionally, the district names vary a lot; in one case the record might say Bradford, Y, when the returned list provides Bradford Yorks.  (For the windows BMD this instance can be added to the returned list in order to save time in the future - perhaps something for the future; or not?).  Furthermore the Principles of Transcribing Data also alludes to the fact that entries should be SAME case as they are in the source that is being transcribed.

For the 1971 transcription currently being transcribed the record format is as follows (hence my initial observations above):

![screen shot 2015-03-30 at 14 34 48](https://cloud.githubusercontent.com/assets/5701185/6897311/b56e0908-d6ea-11e4-8b07-579f61dc76bd.JPG)

**Comment by resnape** [comment]
Hello Steven

I hope you don't mind but I have come up with a minor change to your code (the old code has been commented out and the else return has been amended to invoke capitalizedString) to resolve the 'Month not Capitalised' observation above:

//    else if ( [strtr length] > 1 )
//    {
//        NSString* firstChr = [strtr substringWithRange:NSMakeRange(0, 1)];
//        NSString* endStr = [strtr substringFromIndex:1];
//        return [NSString stringWithFormat:@"%@%@", [firstChr uppercaseString], endStr];
//    }
    else
        return [strtr capitalizedString];

I have tested this and have not found any issues, yet!

I am still pondering on the 'Not all Capitals' observation

**Comment by resnape** [comment]
Hello Steven

I have done some additional research regarding the use of capitalisation of names etc.
To this end I have "recontaminated" my iMAC (under Parallels) with the latest and greatest Windows version of the BMD software.
The implementation to provide Capitulation is somewhat sophisticated, and overly so in my opinion.
![screen shot 2015-03-31 at 07 40 52](https://cloud.githubusercontent.com/assets/5701185/6913813/740a8120-d77c-11e4-9ec5-db55e01ad8e3.JPG)
Above is a screen shot of the main window capability but this can be overridden, which makes this capability superfluous, by setting the case by column, as depicted below.
![screen shot 2015-03-31 at 07 40 23](https://cloud.githubusercontent.com/assets/5701185/6913819/810361b2-d77c-11e4-9e49-e9084a60cf2a.JPG)
I have also looked again at the old (original) version of MacBMD and the implementation reflects the capability provided by MacBMD-X Version 1.0.6.  

Food for thought?

**Comment by resnape** [comment]
Hello Steven

Further to the observation that started this thread and concerning the first observation re: Version 1.0.8, namely 'Not all Capitals'

I have found that If there is an entry after the Middle Name then the Middle Name becomes all Capitals (With ABC ticked),  however, if there is no entry after the Middle Name then the Middle Name is word capitalised (With ABC ticked and as in the example, in the first observation).

**Comment by stwf** [comment]
OK, hopefully this has been addressed in 1.0.9. Thanks
