### ISSUE TITLE
Apostrophe and FreeBMD

### ISSUE THREAD

**Issue by resnape** [stwf/BMD-X#37]
Research into the implementation of the Apostrophe in the FreeBMD character set (ISO8859-1) has identified what I believe to be the manifestation of FreeBMD taking exception and posting a warning - Character not in FreeBMD character set (ISO8859-1): 'Single low-9 quotation mark’, when uploading a MacBMD-X transcription containing a name such as O’Brian.

Initial findings show that Apple uses UTF-16 encoding and appears to have combined the Apostrophe, Right single and Left single quotes to be represented by a single key as Unicode U+2019 (C/C++/Java source code “\u2019”) but which is actually the coding for a Right single quote; hence the warning described above. The reasons appear to be steeped in history and are irrelevant as this time.   FreeBMD appears to expect the Apostrophe to be faithfully represented by Unicode U+0027 (C/C++/Java source code “\u0027”).

**Comment by stwf** [comment]
OK, thanks so much for the research on this. I have attempted a fix of this in 1.0.9. Please let me know how it works.

**Comment by stwf** [comment]
OK, hopefully this has been addressed in 1.0.9. Thanks
